name       : python-setuptools-git
version    : 1.2
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/s/setuptools-git/setuptools-git-1.2.tar.gz : ff64136da01aabba76ae88b050e7197918d8b2139ccbf6144e14d472b9c40445
license    : BSD-3-Clause
component  : programming.python
summary    : Setuptools revision control system plugin for git
description: |
    This is a plugin for setuptools that enables git integration. Once installed, Setuptools can be told to include in a package distribution all the files tracked by git. This is an alternative to explicit inclusion specifications with MANIFEST.in.
builddeps  :
    - git # check
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    git config --global user.email "nobody@nowhere.com"

    pushd $PKG_BUILD_DIR/py2build
        python setup.py test -v
    popd
    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test -v
    popd
