name       : python-setuptools-git
version    : 1.2
release    : 1
source     :
    - https://pypi.python.org/packages/d9/c5/396c2c06cc89d4ce2d8ccf1d7e6cf31b33d4466a7c65a67a992adb3c6f29/setuptools-git-1.2.tar.gz : ff64136da01aabba76ae88b050e7197918d8b2139ccbf6144e14d472b9c40445
license    : BSD-3-Clause
component  : programming.python
summary    : Setuptools revision control system plugin for Git.
description: |
    Setuptools revision control system plugin for Git.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
